# why Numpy? isn't it basically python lists?
Numpy is under the hood written in the programming lang C which is way more faster to use than python 


## Numpy is the backbone of numerical computing in python 

In [2]:
import numpy as np

## Data Types && Attributes

# NumPy's main datatype is ndarray(n-dimensional array)

In [3]:
a1 = np.array([1,2,3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.3,3.3],
              [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5.5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [6]:
a2

array([[1. , 2.3, 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5.5,  6. ],
        [ 7. ,  8. ,  9. ]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

### Anatomy of Numpy Array


It is a very immportant jubject bacause in ML yu=ou need to be sure that the arrays you put in to algorithm mst be in same dimension as the entry

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1

array([1, 2, 3])

In [12]:
a2

array([[1. , 2.3, 3.3],
       [4. , 5. , 6.5]])

In [13]:
a3 

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5.5,  6. ],
        [ 7. ,  8. ,  9. ]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

### .ndim (Number of Dimensions ) 

In [12]:
a1.ndim, a2.ndim, a3.ndim 

(1, 2, 3)

#####  ML algorithm will find patterns in your arrays

In [17]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [18]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

#### ndarray is a universal datatype and veryvery flexible  

## Create a DataFrame from Numpy array


In [15]:
import pandas as pd 

df = pd.DataFrame(a2)

In [16]:
a2, df

(array([[1. , 2.3, 3.3],
        [4. , 5. , 6.5]]),
      0    1    2
 0  1.0  2.3  3.3
 1  4.0  5.0  6.5)

#### pandas can perform manupilations on np.array when import as df within

In [17]:
 e1=np.array([1.3,4])
    

In [44]:
e1

array([1.3, 4. ])

In [47]:
e2 = np.array([[1,2,3],[4,5,6]])

In [48]:
e2

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
df_e2 = pd.DataFrame(e2)
df_e2

0  1  2
0  1  2  3
1  4  5  6

In [50]:
e3 = np.array([[[1,2,3],[4,5,6],
                [1,2,3],[4,5,6]],
               [[9,8,7],[6,5,4],
                [1,2,3],[4,5,6]]])
e3

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4],
        [1, 2, 3],
        [4, 5, 6]]])

In [52]:
e3.ndim

3

In [20]:
e4 = np.arange(72)
e4 = np.reshape(e4, (4,3,2,3))
e4

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]],


       [[[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]]])

In [54]:
e4.ndim

1

## Creating Numpy arrays 

In [21]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [22]:
sample_array.dtype

dtype('int32')

In [24]:
one = np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

#  Shift+ tab opens docstring of cursor's function 

In [25]:
one.dtype

dtype('float64')

In [26]:
type(one)

numpy.ndarray

In [67]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

-----

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).


In [35]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[9, 2, 6, 6, 9],
       [6, 1, 6, 7, 0],
       [1, 3, 1, 3, 8]])

.

In [45]:
rand_array_b = np.random.random((5,3))
rand_array_b

array([[0.16840896, 0.45902306, 0.34212275],
       [0.23245581, 0.64769138, 0.00521181],
       [0.93892178, 0.16411445, 0.42497645],
       [0.6062324 , 0.5012105 , 0.14810775],
       [0.13187258, 0.36574115, 0.45106108]])

In [46]:
rand_array_b.shape

(5, 3)

In [48]:
rand_array_b.ndim

2

In [61]:
rand_array_c = np.random.rand(5,3)
rand_array_c

array([[0.35734296, 0.1833134 , 0.90729278],
       [0.58129672, 0.60006389, 0.47835153],
       [0.51814167, 0.69918083, 0.91719753],
       [0.86564351, 0.42071512, 0.30666758],
       [0.76517197, 0.16722631, 0.41771329]])

------

# Pseudo-random numbers!!!(Seeds)


In [67]:
#np.random.seed()
rand_array_d = np.random.randint(10, size=(5,3))
rand_array_d

array([[5, 3, 1],
       [2, 9, 5],
       [6, 7, 1],
       [1, 3, 6],
       [4, 4, 3]])