# why Numpy? isn't it basically python lists?
Numpy is under the hood written in the programming lang C which is way more faster to use than python 


## Numpy is the backbone of numerical computing in python 

In [1]:
import numpy as np

## Data Types && Attributes

# NumPy's main datatype is ndarray(n-dimensional array)

In [2]:
a1 = np.array([1,2,3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.3,3.3],
              [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5.5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [5]:
a2

array([[1. , 2.3, 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5.5,  6. ],
        [ 7. ,  8. ,  9. ]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

### Anatomy of Numpy Array


It is a very immportant jubject bacause in ML yu=ou need to be sure that the arrays you put in to algorithm mst be in same dimension as the entry

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1

array([1, 2, 3])

In [11]:
a2

array([[1. , 2.3, 3.3],
       [4. , 5. , 6.5]])

In [12]:
a3 

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5.5,  6. ],
        [ 7. ,  8. ,  9. ]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

### .ndim (Number of Dimensions ) 

In [13]:
a1.ndim, a2.ndim, a3.ndim 

(1, 2, 3)

#####  ML algorithm will find patterns in your arrays

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

#### ndarray is a universal datatype and veryvery flexible  

## Create a DataFrame from Numpy array


In [17]:
import pandas as pd 

df = pd.DataFrame(a2)

In [18]:
a2, df

(array([[1. , 2.3, 3.3],
        [4. , 5. , 6.5]]),
      0    1    2
 0  1.0  2.3  3.3
 1  4.0  5.0  6.5)

#### pandas can perform manupilations on np.array when import as df within

In [19]:
 e1=np.array([1.3,4])
    

In [20]:
e1

array([1.3, 4. ])

In [21]:
e2 = np.array([[1,2,3],[4,5,6]])

In [22]:
e2

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
df_e2 = pd.DataFrame(e2)
df_e2

0  1  2
0  1  2  3
1  4  5  6

In [24]:
e3 = np.array([[[1,2,3],[4,5,6],
                [1,2,3],[4,5,6]],
               [[9,8,7],[6,5,4],
                [1,2,3],[4,5,6]]])
e3

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4],
        [1, 2, 3],
        [4, 5, 6]]])

In [25]:
e3.ndim

3

In [26]:
e4 = np.arange(72)
e4 = np.reshape(e4, (4,3,2,3))
e4

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]],


       [[[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]]])

In [27]:
e4.ndim

4

## Creating Numpy arrays 

In [28]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [29]:
sample_array.dtype

dtype('int32')

In [30]:
one = np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

#  Shift+ tab opens docstring of cursor's function 

In [31]:
one.dtype

dtype('float64')

In [32]:
type(one)

numpy.ndarray

In [33]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

-----

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).


In [35]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[8, 6, 4, 0, 8],
       [1, 9, 6, 4, 2],
       [8, 3, 6, 7, 5]])

.

In [36]:
rand_array_b = np.random.random((5,3))
rand_array_b

array([[0.14457583, 0.11130213, 0.48750605],
       [0.9064618 , 0.61217812, 0.31260426],
       [0.02231448, 0.21182329, 0.41975141],
       [0.80731692, 0.20450761, 0.37863425],
       [0.96081077, 0.3751343 , 0.97957274]])

In [37]:
rand_array_b.shape

(5, 3)

In [38]:
rand_array_b.ndim

2

In [39]:
rand_array_c = np.random.rand(5,3)
rand_array_c

array([[0.42507933, 0.71389625, 0.99312172],
       [0.86278248, 0.85958472, 0.54667629],
       [0.5324772 , 0.98591065, 0.31835541],
       [0.85345912, 0.96603102, 0.86111465],
       [0.75478627, 0.06189169, 0.08987416]])

------

# Pseudo-random numbers!!!(Seeds)


In [40]:
np.random.seed(seed = 1)
rand_array_d = np.random.randint(10, size=(5,3))
rand_array_d

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

#### Seeds allow to use random numbers that are reproducable

In [41]:
np.random.seed(678)
rand_array_e = np.random.random((5,3))
rand_array_e

array([[0.5218909 , 0.55011567, 0.70046432],
       [0.53139004, 0.31229631, 0.06709716],
       [0.90591227, 0.87585873, 0.35306843],
       [0.46007908, 0.63008159, 0.65926849],
       [0.28933397, 0.06547582, 0.56666506]])

In [42]:
np.random.seed(1000)
rand_array_f =  np.random.randint(0,1000000000, size=(5,3))
rand_array_f

array([[659662259, 882709079, 493951047],
       [474091200, 860208379,  44058974],
       [997254492, 475890433, 526024125],
       [429448832, 911961945,  58396205],
       [174846504, 404756329, 632195420]])

----

# 3. Viewing arrays & matrices

In [43]:
len(np.unique(rand_array_f)), np.unique(rand_array_f)

(15,
 array([ 44058974,  58396205, 174846504, 404756329, 429448832, 474091200,
        475890433, 493951047, 526024125, 632195420, 659662259, 860208379,
        882709079, 911961945, 997254492]))

numpy.unique
numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None, *, equal_nan=True)[source]

Find the unique elements of an array.

Returns the sorted unique elements of an array. There are three optional outputs in addition to the unique elements:

In [44]:
a1

array([1, 2, 3])

In [45]:
a1[0]

1

In [46]:
a2

array([[1. , 2.3, 3.3],
       [4. , 5. , 6.5]])

In [47]:
a2[0]

array([1. , 2.3, 3.3])

In [48]:
a3

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5.5,  6. ],
        [ 7. ,  8. ,  9. ]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

In [49]:
a3[0] 

array([[1. , 2. , 3. ],
       [4. , 5.5, 6. ],
       [7. , 8. , 9. ]])

----

In [50]:
a3, a3.shape

(array([[[ 1. ,  2. ,  3. ],
         [ 4. ,  5.5,  6. ],
         [ 7. ,  8. ,  9. ]],
 
        [[10. , 11. , 12. ],
         [13. , 14. , 15. ],
         [16. , 17. , 18. ]]]),
 (2, 3, 3))

In [51]:
a3[:2,:2,:2]

array([[[ 1. ,  2. ],
        [ 4. ,  5.5]],

       [[10. , 11. ],
        [13. , 14. ]]])

In [52]:
a4 = np.random.randint(10, size= (2,3,4,5))
a4

array([[[[4, 9, 4, 4, 2],
         [9, 8, 2, 4, 2],
         [5, 5, 4, 0, 4],
         [2, 5, 4, 7, 0]],

        [[4, 7, 1, 0, 2],
         [1, 7, 1, 5, 6],
         [5, 7, 8, 8, 2],
         [2, 9, 6, 3, 3]],

        [[6, 5, 8, 4, 1],
         [0, 9, 1, 8, 8],
         [0, 2, 9, 3, 9],
         [6, 2, 9, 5, 8]]],


       [[[5, 6, 9, 6, 7],
         [6, 3, 4, 8, 1],
         [3, 7, 2, 0, 4],
         [4, 1, 6, 5, 1]],

        [[4, 1, 7, 4, 5],
         [0, 6, 2, 9, 7],
         [0, 8, 0, 5, 3],
         [0, 4, 3, 3, 3]],

        [[6, 4, 7, 2, 4],
         [4, 2, 4, 1, 2],
         [3, 9, 0, 5, 2],
         [1, 0, 6, 8, 9]]]])

In [53]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

### Getting te first four numbers of inner most arrays

In [54]:
a4[:,:,:,:4]

array([[[[4, 9, 4, 4],
         [9, 8, 2, 4],
         [5, 5, 4, 0],
         [2, 5, 4, 7]],

        [[4, 7, 1, 0],
         [1, 7, 1, 5],
         [5, 7, 8, 8],
         [2, 9, 6, 3]],

        [[6, 5, 8, 4],
         [0, 9, 1, 8],
         [0, 2, 9, 3],
         [6, 2, 9, 5]]],


       [[[5, 6, 9, 6],
         [6, 3, 4, 8],
         [3, 7, 2, 0],
         [4, 1, 6, 5]],

        [[4, 1, 7, 4],
         [0, 6, 2, 9],
         [0, 8, 0, 5],
         [0, 4, 3, 3]],

        [[6, 4, 7, 2],
         [4, 2, 4, 1],
         [3, 9, 0, 5],
         [1, 0, 6, 8]]]])

# Manupilating & Comparing Arrays

### Arithmetic

In [55]:
a1

array([1, 2, 3])

In [56]:
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
a1 + one 

array([[2., 3., 4.],
       [2., 3., 4.]])

In [58]:
 a1 - one

array([[0., 1., 2.],
       [0., 1., 2.]])

In [59]:
a1 * one 

array([[1., 2., 3.],
       [1., 2., 3.]])

In [60]:
a1

array([1, 2, 3])

In [61]:
a2 

array([[1. , 2.3, 3.3],
       [4. , 5. , 6.5]])

In [62]:
a1 *a2

array([[ 1. ,  4.6,  9.9],
       [ 4. , 10. , 19.5]])

In [63]:
# How can you reshape a2 to be compatible w a3 ?
# Search:"How to reshape numpy array?"


a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1 / one

In [ ]:
a1 / a2

In [ ]:
a1 // a2

In [ ]:
a2 ** a1

In [ ]:
a1

In [ ]:
a2

In [ ]:
a2 % a1

#### Exponantials

In [ ]:
np.exp(a1)

#### Logarithms

In [64]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation
The formation of a number of things in a cluster

In [65]:
list_list = [1,2,3]
type(list_list)

list

In [66]:
sum(list_list)

6

In [67]:
sum(a1)

6

In [68]:
np.sum(a1)

6

Use Python's methods(`sum()`) on Python datatypes & use NumPy's methods(`np.sum()`) on NumPy's Dattypes

In [69]:
#Create a massive NumPy Array
massive_array = np.random.random(100000)
massive_array.size

100000

In [70]:
massive_array[:10]

array([0.72540315, 0.54143928, 0.48258449, 0.47647761, 0.44603283,
       0.81607006, 0.27435149, 0.06196201, 0.96029634, 0.45811813])

`%timeit`is one of the magic commands of the jupyter notebook(times  how long a particular set of codes takes to run)

In [71]:
%timeit sum(massive_array) #Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()


11.2 ms ± 404 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
46.6 µs ± 7.09 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [72]:
a2

array([[1. , 2.3, 3.3],
       [4. , 5. , 6.5]])

In [73]:
np.mean(a2)

3.6833333333333336

In [74]:
np.min(a2)

1.0

In [75]:
# Standart deviation = a measure of how spread out a group of numbers is from the mean.
np.std(a2)


1.7808393776219373

In [76]:
# Variance = Measure of the average degree to which each number is different to the mean. 
# Higher variance = Higher range of numbers.
# Lower variance = Lower range of numbers.
np.var(a2)

3.1713888888888895

In [77]:
# Standart Deviation = Squareroot of variance 
if  np.sqrt(np.var(a2)) == np.std(a2):
    print("True")

True


In [78]:
# Demo of std & var
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([1,2,3,4,5,6])

In [79]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 2.9166666666666665)

In [80]:
np.std(high_var_array),np.std(low_var_array)

(2072.711623024829, 1.707825127659933)

In [81]:
np.mean(high_var_array),np.mean(low_var_array)

(1600.1666666666667, 3.5)