# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
oned_array = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
twod_array = np.array([[1,2,3],
                       [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
threed_array = np.array([[[1,2,3],
                          [4,5,6]],
                         [[3,2,1],
                          [6,5,4]]])
oned_array,twod_array,threed_array

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[3, 2, 1],
         [6, 5, 4]]]))

In [3]:
print(f"oned_array: {oned_array.ndim}"), print(f"twod_array: {twod_array.ndim}"),print(f"threed_array: {threed_array.ndim}")

oned_array: 1
twod_array: 2
threed_array: 3


(None, None, None)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
oned_array.ndim, oned_array.dtype, oned_array.size,type(oned_array)

(1, dtype('int32'), 3, numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
twod_array.ndim, twod_array.dtype, twod_array.size, type(twod_array)

(2, dtype('int32'), 6, numpy.ndarray)

In [9]:
# Attributes of 3-dimensional array
threed_array.ndim, threed_array.dtype, threed_array.size, type(threed_array)

(3, dtype('int32'), 12, numpy.ndarray)

In [13]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 
df = pd.DataFrame(twod_array)
df

0  1  2
0  1  2  3
1  4  5  6

In [15]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7,2,3))
zeros.shape, zeros

((7, 2, 3),
 array([[[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]))

In [27]:
# Create an array within a range of 0 and 100 with step 3
array_to_hundred = np.arange(0,100,3)
array_to_hundred

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [29]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_array_a = np.random.randint(10, size= (7,2))
rand_array_a.shape

(7, 2)

In [31]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_floats = np.random.random((3,5))
random_floats, random_floats.shape

(array([[0.09584263, 0.90170156, 0.28071127, 0.43158163, 0.80990054],
        [0.51630204, 0.33420386, 0.59715396, 0.13886042, 0.61847741],
        [0.88839223, 0.23500356, 0.21642366, 0.59870701, 0.37798087]]),
 (3, 5))

In [38]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_b = np.random.randint(10, size= (4,6))
random_array_b, random_array_b.shape

(array([[6, 3, 7, 4, 6, 9],
        [2, 6, 7, 4, 3, 7],
        [7, 2, 5, 4, 1, 7],
        [5, 1, 4, 0, 9, 5]]),
 (4, 6))

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [42]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

random_array_c = np.random.randint(10, size=(3,7))
random_array_c
# Find the unique numbers in the array you just created
print(f"unique numbers are : {np.unique(random_array_c)}"), random_array_c

unique numbers are : [0 1 2 4 6 7 8 9]


(None,
 array([[0, 7, 2, 2, 0, 4, 9],
        [6, 9, 8, 6, 8, 7, 1],
        [0, 6, 6, 7, 4, 2, 7]]))

In [43]:
# Find the 0'th index of the latest array you created
random_array_c[0]

array([0, 7, 2, 2, 0, 4, 9])

In [44]:
# Get the first 2 rows of latest array you created
random_array_c[0:2]

array([[0, 7, 2, 2, 0, 4, 9],
       [6, 9, 8, 6, 8, 7, 1]])

In [48]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_c[0:2, 0:2]

array([[0, 7],
       [6, 9]])

In [53]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_d = np.random.randint(10,size=(3,5))
ones_b = np.ones(shape = (3,5))
random_array_d,random_array_d.shape, ones_b, ones_b.shape

(array([[7, 8, 4, 0, 2],
        [9, 7, 5, 7, 8],
        [3, 0, 0, 9, 3]]),
 (3, 5),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 (3, 5))

In [54]:
# Add the two arrays together
random_array_d + ones_b

array([[ 8.,  9.,  5.,  1.,  3.],
       [10.,  8.,  6.,  8.,  9.],
       [ 4.,  1.,  1., 10.,  4.]])

In [55]:
# Create another array of ones of shape (5, 3)

ones_c = np.ones(shape=(5,3))
ones_c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
# Try add the array of ones and the other most recent array together
random_array_d + ones_c

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [59]:
# Create another array of ones of shape (3, 5)
ones_d = np.ones(shape=(3,5))

In [60]:
# Subtract the new array of ones from the other most recent array
random_array_d - ones_d

array([[ 6.,  7.,  3., -1.,  1.],
       [ 8.,  6.,  4.,  6.,  7.],
       [ 2., -1., -1.,  8.,  2.]])

In [61]:
# Multiply the ones array with the latest array
random_array_d * ones_d

array([[7., 8., 4., 0., 2.],
       [9., 7., 5., 7., 8.],
       [3., 0., 0., 9., 3.]])

In [62]:
# Take the latest array to the power of 2 using '**'
random_array_d ** 2

array([[49, 64, 16,  0,  4],
       [81, 49, 25, 49, 64],
       [ 9,  0,  0, 81,  9]])

In [63]:
# Do the same thing with np.square()
np.square(random_array_d)

array([[49, 64, 16,  0,  4],
       [81, 49, 25, 49, 64],
       [ 9,  0,  0, 81,  9]])

In [64]:
# Find the mean of the latest array using np.mean()
np.mean(random_array_d)

4.8

In [65]:
# Find the maximum of the latest array using np.max()
np.max(random_array_d)

9

In [66]:
# Find the minimum of the latest array using np.min()
np.min(random_array_d)

0

In [67]:
# Find the standard deviation of the latest array
np.std(random_array_d)

3.2083225108042575

In [68]:
# Find the variance of the latest array
np.var(random_array_d)

10.293333333333335

In [69]:
random_array_d

array([[7, 8, 4, 0, 2],
       [9, 7, 5, 7, 8],
       [3, 0, 0, 9, 3]])

In [70]:
# Reshape the latest array to (3, 5, 1)
random_array_d.reshape(3,5,1)

array([[[7],
        [8],
        [4],
        [0],
        [2]],

       [[9],
        [7],
        [5],
        [7],
        [8]],

       [[3],
        [0],
        [0],
        [9],
        [3]]])

In [71]:
random_array_d

array([[7, 8, 4, 0, 2],
       [9, 7, 5, 7, 8],
       [3, 0, 0, 9, 3]])

In [72]:
# Transpose the latest array
random_array_d.T

array([[7, 9, 3],
       [8, 7, 0],
       [4, 5, 0],
       [0, 7, 9],
       [2, 8, 3]])

What does the transpose do?

In [74]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array_e = np.random.randint(10, size=(3,3))
random_array_f = np.random.randint(10, size= (3,2))
random_array_e, random_array_f

(array([[6, 1, 2],
        [0, 4, 0],
        [7, 0, 0]]),
 array([[1, 1],
        [5, 6],
        [4, 0]]))

In [79]:
random_array_e.shape, random_array_f.shape

((3, 3), (3, 2))

In [78]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_e,random_array_f)

array([[19, 12],
       [20, 24],
       [ 7,  7]])

In [84]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand_a = np.random.randint(10, size=(4,3))
rand_b = np.random.randint(10, size=(4,3))
rand_a, rand_b

(array([[2, 9, 2],
        [2, 3, 6],
        [3, 8, 0],
        [7, 6, 1]]),
 array([[7, 0, 8],
        [8, 1, 6],
        [9, 2, 6],
        [9, 8, 3]]))

In [82]:
# Perform a dot product on the two newest arrays you created
np.dot(rand_a, rand_b)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [83]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arrays_dotted = np.dot(rand_a, rand_b.T)
arrays_dotted

array([[11, 15, 21,  9],
       [79, 74, 97, 50],
       [72, 51, 54, 39],
       [64, 32, 25, 29]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [86]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand_c = np.random.randint(10, size= (5,5))
rand_d =np.random.randint(10, size= (5,5))
rand_c, rand_d

(array([[5, 5, 2, 5, 7],
        [1, 4, 0, 0, 4],
        [2, 3, 2, 0, 0],
        [4, 5, 2, 8, 4],
        [7, 0, 4, 2, 0]]),
 array([[3, 4, 6, 0, 2],
        [1, 8, 9, 5, 9],
        [2, 7, 7, 1, 5],
        [6, 1, 9, 1, 9],
        [0, 7, 0, 8, 5]]))

In [87]:
# Compare the two arrays with '>'
rand_c < rand_d

array([[False, False,  True, False, False],
       [False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True, False,  True, False,  True],
       [False,  True, False,  True,  True]])

In [88]:
rand_c > rand_d

array([[ True,  True, False,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False,  True, False],
       [ True, False,  True, False, False]])

What happens when you compare the arrays with `>`?

In [89]:
# Compare the two arrays with '>='
rand_c >= rand_d

array([[ True,  True, False,  True,  True],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [False,  True, False,  True, False],
       [ True, False,  True, False, False]])

In [90]:
# Find which elements of the first array are greater than 7
rand_c > 7

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False, False, False, False]])

In [91]:
# Which parts of each array are equal? (try using '==')
rand_c == rand_d

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [94]:
# Sort one of the arrays you just created in ascending order
np.sort(rand_c)

array([[2, 5, 5, 5, 7],
       [0, 0, 1, 4, 4],
       [0, 0, 2, 2, 3],
       [2, 4, 4, 5, 8],
       [0, 0, 2, 4, 7]])

In [95]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand_c)

array([[2, 0, 1, 3, 4],
       [2, 3, 0, 1, 4],
       [3, 4, 0, 2, 1],
       [2, 0, 4, 1, 3],
       [1, 4, 3, 2, 0]], dtype=int64)

In [96]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand_c)

18

In [97]:
# Find the index with the minimum value in
np.argmin(rand_c)

7

In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created



In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.