# why Numpy? isn't it basically python lists?
Numpy is under the hood written in the programming lang C which is way more faster to use than python 


## Numpy is the backbone of numerical computing in python 

In [106]:
import numpy as np

## Data Types && Attributes

# NumPy's main datatype is ndarray(n-dimensional array)

In [107]:
a1 = np.array([1,2,3])

In [108]:
type(a1)

numpy.ndarray

In [109]:
a2 = np.array([[1,2.3,3.3],
              [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5.5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [110]:
a2

array([[1. , 2.3, 3.3],
       [4. , 5. , 6.5]])

In [111]:
a3

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5.5,  6. ],
        [ 7. ,  8. ,  9. ]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

### Anatomy of Numpy Array


It is a very immportant jubject bacause in ML yu=ou need to be sure that the arrays you put in to algorithm mst be in same dimension as the entry

In [112]:
a1.shape

(3,)

In [113]:
a2.shape

(2, 3)

In [114]:
a3.shape

(2, 3, 3)

In [115]:
a1

array([1, 2, 3])

In [116]:
a2

array([[1. , 2.3, 3.3],
       [4. , 5. , 6.5]])

In [117]:
a3 

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5.5,  6. ],
        [ 7. ,  8. ,  9. ]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

### .ndim (Number of Dimensions ) 

In [118]:
a1.ndim, a2.ndim, a3.ndim 

(1, 2, 3)

#####  ML algorithm will find patterns in your arrays

In [119]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [120]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [121]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

#### ndarray is a universal datatype and veryvery flexible  

## Create a DataFrame from Numpy array


In [122]:
import pandas as pd 

df = pd.DataFrame(a2)

In [123]:
a2, df

(array([[1. , 2.3, 3.3],
        [4. , 5. , 6.5]]),
      0    1    2
 0  1.0  2.3  3.3
 1  4.0  5.0  6.5)

#### pandas can perform manupilations on np.array when import as df within

In [124]:
 e1=np.array([1.3,4])
    

In [125]:
e1

array([1.3, 4. ])

In [126]:
e2 = np.array([[1,2,3],[4,5,6]])

In [127]:
e2

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
df_e2 = pd.DataFrame(e2)
df_e2

0  1  2
0  1  2  3
1  4  5  6

In [129]:
e3 = np.array([[[1,2,3],[4,5,6],
                [1,2,3],[4,5,6]],
               [[9,8,7],[6,5,4],
                [1,2,3],[4,5,6]]])
e3

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4],
        [1, 2, 3],
        [4, 5, 6]]])

In [130]:
e3.ndim

3

In [131]:
e4 = np.arange(72)
e4 = np.reshape(e4, (4,3,2,3))
e4

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]],


       [[[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]]])

In [132]:
e4.ndim

4

## Creating Numpy arrays 

In [133]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [134]:
sample_array.dtype

dtype('int32')

In [135]:
one = np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

#  Shift+ tab opens docstring of cursor's function 

In [136]:
one.dtype

dtype('float64')

In [137]:
type(one)

numpy.ndarray

In [138]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [139]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

-----

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).


In [140]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[4, 9, 4, 4, 2],
       [9, 8, 2, 4, 2],
       [5, 5, 4, 0, 4]])

.

In [141]:
rand_array_b = np.random.random((5,3))
rand_array_b

array([[0.0351059 , 0.85505825, 0.65725351],
       [0.76568299, 0.55408724, 0.88509294],
       [0.90419762, 0.0104217 , 0.07455674],
       [0.24462921, 0.13330475, 0.6979251 ],
       [0.39820488, 0.88312219, 0.18100751]])

In [142]:
rand_array_b.shape

(5, 3)

In [143]:
rand_array_b.ndim

2

In [144]:
rand_array_c = np.random.rand(5,3)
rand_array_c

array([[0.43249917, 0.0181432 , 0.69143786],
       [0.46969065, 0.12822219, 0.89133705],
       [0.91820362, 0.07312099, 0.04544794],
       [0.4385729 , 0.60172093, 0.31022703],
       [0.68190824, 0.20901315, 0.5196043 ]])

------

# Pseudo-random numbers!!!(Seeds)


In [145]:
np.random.seed(seed = 1)
rand_array_d = np.random.randint(10, size=(5,3))
rand_array_d

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

#### Seeds allow to use random numbers that are reproducable

In [146]:
np.random.seed(678)
rand_array_e = np.random.random((5,3))
rand_array_e

array([[0.5218909 , 0.55011567, 0.70046432],
       [0.53139004, 0.31229631, 0.06709716],
       [0.90591227, 0.87585873, 0.35306843],
       [0.46007908, 0.63008159, 0.65926849],
       [0.28933397, 0.06547582, 0.56666506]])

In [147]:
np.random.seed(1000)
rand_array_f =  np.random.randint(0,1000000000, size=(5,3))
rand_array_f

array([[659662259, 882709079, 493951047],
       [474091200, 860208379,  44058974],
       [997254492, 475890433, 526024125],
       [429448832, 911961945,  58396205],
       [174846504, 404756329, 632195420]])

----

# 3. Viewing arrays & matrices

In [148]:
len(np.unique(rand_array_f)), np.unique(rand_array_f)

(15,
 array([ 44058974,  58396205, 174846504, 404756329, 429448832, 474091200,
        475890433, 493951047, 526024125, 632195420, 659662259, 860208379,
        882709079, 911961945, 997254492]))

numpy.unique
numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None, *, equal_nan=True)[source]

Find the unique elements of an array.

Returns the sorted unique elements of an array. There are three optional outputs in addition to the unique elements:

In [152]:
a1

array([1, 2, 3])

In [149]:
a1[0]

1

In [153]:
a2

array([[1. , 2.3, 3.3],
       [4. , 5. , 6.5]])

In [150]:
a2[0]

array([1. , 2.3, 3.3])

In [154]:
a3

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5.5,  6. ],
        [ 7. ,  8. ,  9. ]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

In [151]:
a3[0] 

array([[1. , 2. , 3. ],
       [4. , 5.5, 6. ],
       [7. , 8. , 9. ]])

----

In [155]:
a3

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5.5,  6. ],
        [ 7. ,  8. ,  9. ]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

In [168]:
a3[:2,:2,:2]

array([[[ 1. ,  2. ],
        [ 4. ,  5.5]],

       [[10. , 11. ],
        [13. , 14. ]]])